version: '3'
services:
  #node:
    #restart: always
    #build: .
    #ports:
      #- 8080:8080
    #volumes:
      #- ./:/code
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=travelblog
    ports:
      - 27017:27017
    #volumes:
      #- mongodb:/data/db
volumes:
  mongodb:
